### ISSUE TITLE
Metadata view broken on master demo instance

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#439]
Opening a metadata detail page raises an error on master demo.
https://master.demo.geonode.org/layers/gn:View_monitoring2015_Geoserver/metadata_detail

![image](https://user-images.githubusercontent.com/571129/75270333-adf24e00-57fa-11ea-88f7-5aba4491998e.png)

**Comment by afabiani** [comment]
It looks an issue of the DB. Somehow there two objects on the db for this layer.

```
Internal Server Error: /layers/gn:View_monitoring2015_Geoserver/metadata_detail
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/src/geonode/geonode/layers/views.py", line 1471, in layer_metadata_detail
    _PERMISSION_MSG_METADATA)
  File "/usr/src/geonode/geonode/layers/views.py", line 193, in _resolve_layer
    **kwargs)
  File "/usr/src/geonode/geonode/utils.py", line 884, in resolve_object
    obj = get_object_or_404(model, **query)
  File "/usr/local/lib/python2.7/site-packages/django/shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 384, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one Layer -- it returned 2!
```
Opened issue on GeoNode

**Comment by afabiani** [comment]
ref. https://github.com/GeoNode/geonode/pull/5798
