### ISSUE TITLE
Investigate issues between GeoNode master and Geoserver 2.16.x

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode#456]
@afabiani please investigate what are the issues you faced between GN and GS 2.16.x.
If I remember correctly you said something about REST API and /or Geoserver AuthN. @aaime confirmed that there has been an upgrade of Spring Security between GS 2.16.2 and 2.16.x.

**Comment by afabiani** [comment]
Currently, I identified two issues with GeoServer 2.16.x:

1. Thumbnails are not generated; this is probably caused by the unique remaining custom module on geoserver-ext which are a bunch of  rest endpoints used by GeoNode to let GeoServer creating the thumbnail. The call gives an "HTTP Status 404 – Not Found" error. It is worth noticing that the print still works. This must be further investigated but I guess it shouldn't be a big deal to fix it somehow on geoserver-ext.

2. The editing of the features from MapStore returns a NullPointer Exception; this is very likely a bug on GeoServer. The stack trace reports a "Null DataStore Transaction" from GeoServer itself.

**Comment by aaime** [comment]
@afabiani about WFS transactions, can you isolate a reproducible test test, small dataset + transaction failing?

**Comment by afabiani** [comment]
@aaime roger. Is it ok to put it here or I should open a JIRA?

**Comment by afabiani** [comment]
- Data sample: tasmania_water_bodies (see attached file), ingested on a Postgres DB
 - Request:

`curl "http://localhost:8000/proxy/?url=http^%^3A^%^2F^%^2Flocalhost^%^3A8080^%^2Fgeoserver^%^2Fows^%^3Faccess_token^%^3DudqjkyXKAyxswnnU4z79iP6vr78kKM" -H "Connection: keep-alive" -H "Pragma: no-cache" -H "Cache-Control: no-cache" -H "Accept: application/json, text/plain, */*" -H "Sec-Fetch-Dest: empty" -H "X-CSRFToken: kLFtwxDSMHld8m524VUZvUXDdJHf1ohRliVwEO3Vk7mk6XsWpNYH2cJpZdcC7Sa3" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" -H "DNT: 1" -H "Content-Type: application/xml" -H "Origin: http://localhost:8000" -H "Sec-Fetch-Site: same-origin" -H "Sec-Fetch-Mode: cors" -H "Referer: http://localhost:8000/maps/new?layer=geonode:tasmania_water_bodies^&storeType=dataStore" -H "Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,it;q=0.7" -H "Cookie: JSESSIONIDELA=5687C135E2408E5604F50A7563D43576; JSESSIONIDSSOELA=F0E72D349CE0C262B5B2D4131C4D6134; CUSTOM_SSO_TICKET=1566547289438; CUSTOM_SSO_APP_TAG_NAME=ELA; adscsrf=410b1737-4978-433d-90ce-3871b52808cc; JSESSIONID=1F6562FDCC635AE97AB52E5B567AD3C8; viewed_cookie_policy=yes; _xsrf=2^|d6ee332b^|6155da673f0814afb1180c743de5a714^|1585260683; username-localhost-8888=^\^"2^|1:0^|10:1585813037^|23:username-localhost-8888^|44:MzVjNTc4ODU5NzI1NGJkMWEyZmZmOGUwM2JiNjIzNjQ=^|ea49b2fd89e89027d8b8ebb72af497ed2544c58c0bfc6c2efa0ad9223e0a86a1^\^"; csrftoken=kLFtwxDSMHld8m524VUZvUXDdJHf1ohRliVwEO3Vk7mk6XsWpNYH2cJpZdcC7Sa3; sessionid=jijabo3l8g3c201apr9q1a8lo9pd4h89" --data-binary "^<wfs:Transaction service=^\^"WFS^\^" version=^\^"1.1.0^\^" xmlns:wfs=^\^"http://www.opengis.net/wfs^\^" xmlns:gml=^\^"http://www.opengis.net/gml^\^" xmlns:ogc=^\^"http://www.opengis.net/ogc^\^" xmlns:xsi=^\^"http://www.w3.org/2001/XMLSchema-instance^\^" xsi:schemaLocation=^\^"http://www.opengis.net/wfs^\^" xmlns:geonode=^\^"http://www.geonode.org/^\^"^>^<wfs:Update typeName=^\^"geonode:tasmania_water_bodies^\^"^>^<wfs:Property^>^<wfs:Name^>the_geom^</wfs:Name^>^<wfs:Value^>^<gml:MultiPolygon srsName=^\^"EPSG:4326^\^"^>^<gml:polygonMember^>^<gml:Polygon srsName=^\^"EPSG:4326^\^"^>^<gml:exterior^>^<gml:LinearRing^>^<gml:posList^>146.284424 -43.031944000000024 146.265808 -43.029442 146.257751 -43.02166700000002 146.252197 -43.018890000000006 146.243561 -43.017776000000005 146.23053 -43.02166700000002 146.21524 -43.02417 146.20968600000003 -43.02194200000002 146.209961 -43.015007 146.21579 -42.991111999999994 146.21524 -42.985001000000004 146.213593 -42.97943900000002 146.21109 -42.97471600000002 146.207458 -42.970276 146.193024 -42.959724 146.181915 -42.95472000000001 146.166931 -42.95139300000001 146.1586 -42.950554000000004 146.123016 -42.95111100000002 146.11636400000003 -42.94888300000001 146.11273200000002 -42.944717000000004 146.110229 -42.939720000000015 146.101349 -42.932777000000016 146.094971 -42.92972600000001 146.084961 -42.92277500000001 146.054138 -42.89778100000001 146.041656 -42.88666500000002 146.038025 -42.88221700000002 146.035522 -42.877495000000025 146.035248 -42.86528000000002 146.03665200000003 -42.852226 146.034424 -42.84027900000002 146.030823 -42.836113000000005 146.026367 -42.83250400000001 146.018036 -42.83167300000001 146.010529 -42.832779 146.003876 -42.83472400000001 145.995514 -42.835274 145.990784 -42.83167300000001 145.990234 -42.82556200000002 145.996338 -42.81527700000001 146.000549 -42.805275 145.997192 -42.80027800000001 145.984406 -42.789725999999995 145.981079 -42.785561000000015 145.976898 -42.77500200000002 145.97995 -42.770278999999995 145.985504 -42.767776 145.994965 -42.76805900000002 146.002472 -42.769447000000014 146.008881 -42.77249900000002 146.025818 -42.78666700000001 146.032196 -42.78889500000002 146.040802 -42.788338 146.061646 -42.783333000000006 146.068848 -42.785004 146.074402 -42.78778100000002 146.086914 -42.79999500000002 146.109131 -42.825279000000016 146.117188 -42.832222000000016 146.122742 -42.83444200000002 146.131073 -42.835274 146.139709 -42.834999 146.147217 -42.833061 146.16302500000003 -42.831390000000006 146.170532 -42.83361100000001 146.174988 -42.837219000000005 146.176636 -42.841942 146.17746 -42.84805299999999 146.173309 -42.852226 146.165802 -42.853333000000006 146.155243 -42.859169 146.141937 -42.86306000000002 146.12912 -42.858612000000015 146.118011 -42.85278300000002 146.11077900000004 -42.851395000000004 146.102173 -42.852501 146.098297 -42.85500300000002 146.097198 -42.861389 146.102173 -42.871666000000005 146.111359 -42.878883000000016 146.121338 -42.884445 146.15249633789065 -42.88451779606897 146.146942 -42.899445 146.154968 -42.907219 146.164978 -42.91444400000002 146.20193481445312 -42.90162162590301 146.181366 -42.923058000000005 146.195251 -42.92610900000001 146.204681 -42.92639200000001 146.220795 -42.92472099999999 146.22744800000004 -42.92277500000001 146.233032 -42.92027999999999 146.241913 -42.91361200000001 146.23077392578128 -42.878480017739044 146.260529 -42.89194500000001 146.265533 -42.888611000000004 146.272217 -42.886948 146.281372 -42.886948 146.289703 -42.888054 146.300812 -42.893616 146.308014 -42.902779000000024 146.308594 -42.908333 146.30218500000004 -42.925278000000006 146.301086 -42.931388999999996 146.301636 -42.937500000000014 146.303314 -42.94305399999999 146.307739 -42.94666300000001 146.320801 -42.95111100000002 146.330261 -42.95139300000001 146.352753 -42.947777000000016 146.360229 -42.94916500000001 146.361908 -42.95472000000001 146.358002 -42.95944200000001 146.347473 -42.96555300000002 146.335785 -42.969994 146.331085 -42.973328 146.328033 -42.978050000000025 146.329681 -42.98361200000001 146.33609 -42.985832 146.36496 -42.99250000000001 146.371338 -42.99472000000001 146.383331 -43.00055700000001 146.389984 -43.00278500000002 146.39444 -43.00639300000001 146.391357 -43.01111600000001 146.383881 -43.012222 146.36856100000003 -43.02083600000002 146.35522500000002 -43.024719000000005 146.339142 -43.02638999999999 146.332458 -43.028336 146.323853 -43.02860999999999 146.31301900000003 -43.02305600000002 146.306366 -43.02083600000002 146.298859 -43.022774 146.290253 -43.029442 146.284424 -43.031944000000024^</gml:posList^>^</gml:LinearRing^>^</gml:exterior^>^</gml:Polygon^>^</gml:polygonMember^>^</gml:MultiPolygon^>^</wfs:Value^>^</wfs:Property^>^<ogc:Filter^>^<ogc:FeatureId fid=^\^"tasmania_water_bodies.2^\^"/^>^</ogc:Filter^>^</wfs:Update^>^</wfs:Transaction^>" --compressed`

 - Response

```
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://localhost:8080/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd?access_token=udqjkyXKAyxswnnU4z79iP6vr78kKM">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>java.lang.NullPointerException</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

 - Stack trace

```
03 Apr 13:50:35 INFO [geoserver.flow] - Request [WFS 1.1.0 Transaction] starting, processing through flow controllers
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller BasicOWSController(wfs.getfeature.=application/msexcel,org.geoserver.flow.controller.SimpleThreadBlocker@76e83314)
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller BasicOWSController(wfs.getfeature.=application/msexcel,org.geoserver.flow.controller.SimpleThreadBlocker@76e83314)
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller org.geoserver.flow.controller.UserConcurrentFlowController@561cb157
03 Apr 13:50:35 DEBUG [geoserver.flow] - UserFlowController(6,GS_CFLOW_-bc93876:171404d972b:-7ffb) queue size 1
03 Apr 13:50:35 DEBUG [geoserver.flow] - UserFlowController(6,GS_CFLOW_-bc93876:171404d972b:-7ffb) total queues 3
03 Apr 13:50:35 DEBUG [geoserver.flow] - UserFlowController(6) purged 2 stale queues
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller org.geoserver.flow.controller.UserConcurrentFlowController@561cb157
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller BasicOWSController(wms.getmap,org.geoserver.flow.controller.SimpleThreadBlocker@466a2c25)
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller BasicOWSController(wms.getmap,org.geoserver.flow.controller.SimpleThreadBlocker@466a2c25)
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller BasicOWSController(gwc,org.geoserver.flow.controller.SimpleThreadBlocker@68b5abf9)
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller BasicOWSController(gwc,org.geoserver.flow.controller.SimpleThreadBlocker@68b5abf9)
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] checking flow controller GlobalFlowController(org.geoserver.flow.controller.SimpleThreadBlocker@5ff24568)
03 Apr 13:50:35 DEBUG [geoserver.flow] - Request [WFS 1.1.0 Transaction] passed flow controller GlobalFlowController(org.geoserver.flow.controller.SimpleThreadBlocker@5ff24568)
03 Apr 13:50:35 INFO [geoserver.flow] - Request control-flow performed, running requests: 1, blocked requests: 0
03 Apr 13:50:35 DEBUG [geoserver.geofence] - Admin level access, not applying default style for this request
03 Apr 13:50:35 ERROR [geoserver.ows] -
org.geoserver.wfs.WFSException: java.lang.NullPointerException
        at org.geoserver.wfs.Transaction.transaction(Transaction.java:98)
        at org.geoserver.wfs.DefaultWebFeatureService.transaction(DefaultWebFeatureService.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:50)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy170.transaction(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:877)
        at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:265)
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69)
        at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:70)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
        at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:142)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
        at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
        at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
        at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:174)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
        at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
        at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
        at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:101)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:47)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.geoserver.wfs.Transaction.getDatastoreTransaction(Transaction.java:526)
        at org.geoserver.wfs.Transaction.execute(Transaction.java:135)
        at org.geoserver.wfs.Transaction.transaction(Transaction.java:92)
        ... 117 more
03 Apr 13:50:35 DEBUG [geoserver.filters] - Compressing output for mimetype: application/xml
03 Apr 13:50:35 INFO [geoserver.flow] - releasing flow controllers for [WFS 1.1.0 Transaction]
03 Apr 13:50:35 INFO [geoserver.flow] - Request completed, running requests: 0, blocked requests: 0
[taz_shapes.zip](https://github.com/geosolutions-it/geonode/files/4427666/taz_shapes.zip)

```
